go_import_path: github.com/kevinburke/multi-emailer
language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - master

script: make diff race-test

cache:
  directories:
    - $GOPATH/pkg
