# This is used to encrypt sessions and next page URLs before serving them to
# the client.
#
# This should be a hex string that's exactly 64 bytes long. For example:
#
#   d7211b215341871968869dontusethisc0ff1789fc88e0ac6e296ba36703edf8
#
# Don't reuse that key - you can generate a random key by running:
#
#   openssl rand -hex 32
#
# If no secret key is present, we'll generate one when the server starts.
# However, this means that sessions and any in-progress paging attempts will
# error when the server restarts.
#
# If a server key is present, but invalid, the server will not start.
secret_key: fill-in-key

# What users type in their browser to reach your site (scheme+host)
public_host: http://localhost:8048

# To create/configure Google credentials, see
# https://github.com/saintpete/logrole/blob/master/docs/google.md
google_client_id:     customdomain.apps.googleusercontent.com
google_client_secret: W-secretkey
