# This is used to encrypt sessions and next page URLs before serving them to
# the client.
#
# This should be a hex string that's exactly 64 bytes long. For example:
#
#   d7211b215341871968869dontusethisc0ff1789fc88e0ac6e296ba36703edf8
#
# Don't reuse that key - you can generate a random key by running:
#
#   openssl rand -hex 32
#
# If no secret key is present, we'll generate one when the server starts.
# However, this means that sessions and any in-progress paging attempts will
# error when the server restarts.
#
# If a server key is present, but invalid, the server will not start.
secret_key: fill-in-key

# Local port to listen on. If omitted, check the PORT environment variable, if
# that is not present, then 8048 is used.
port: 8048

# What users type in their browser to reach your site (scheme+host)
public_host: https://localhost:8048

# To create/configure Google credentials, see
# https://github.com/saintpete/logrole/blob/master/docs/google.md
#
# Then, enable the GMail API for your project by going here:
# https://console.developers.google.com/apis/api/gmail.googleapis.com/overview
# and clicking "Enable" at the top of the screen.
google_client_id:     customdomain.apps.googleusercontent.com
google_client_secret: W-secretkey

# Disable Google authentication, if you want to render the homepage for local
# development. You can't send emails if this variable is set to true.
# no_google_auth: true

title: My Super Awesome Multi Emailer

groups:
    - id: dotcom
      name: Dot Com Email Addresses
      recipients:
          - email: Kevin Burke <kevin@example.com>
            opening_line: Hi Kevin
          - email: Abe Lincoln <abe@example.com>
            opening_line: President Lincoln
          - email: Margaret Hamilton <margaret@example.com>
            opening_line: Mrs. Hamilton
            cc:
              - Margaret Hamilton's Aide <margaret+aide@example.com>
    - id: dotorg
      name: Dot Org Email List
      recipients:
          - email: Kevin Burke <kevin@example.org>
            opening_line: Hi Kevin
          - email: Abe Lincoln <abe@example.org>
            opening_line: President Lincoln
          - email: Margaret Hamilton <margaret@example.org>
            opening_line: Mrs. Hamilton
