# App Engine tries to vendor these, but it can't deploy them in the vendor
# folder.
ignored = [
    "google.golang.org/appengine",
    "google.golang.org/appengine/urlfetch",
]

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/inconshreveable/log15"
  version = "2.13.0"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/jpoehls/gophermail"

[[constraint]]
  name = "github.com/kevinburke/google-oauth-handler"
  version = "0.4.0"

[[constraint]]
  name = "github.com/kevinburke/handlers"
  version = "0.39.0"

[[constraint]]
  name = "github.com/kevinburke/rest"
  version = "2.1"

[[constraint]]
  branch = "master"
  name = "github.com/kevinburke/semaphore"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
